# Generated by Django 4.1.5 on 2023-02-14 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBitirme', '0003_category_card_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Yorum Başlığı')),
                ('text', models.TextField(max_length=1000, verbose_name='Yorum')),
                ('user', models.CharField(max_length=50, verbose_name='Yorum Yapan')),
                ('date_now', models.DateTimeField(auto_now_add=True, verbose_name='Paylaşım Zamanı')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBitirme.card', verbose_name='Kart')),
            ],
        ),
    ]
