# Generated by Django 4.1.5 on 2023-02-22 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appBitirme', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=50, region=None, verbose_name='Şifre')),
                ('password', models.CharField(max_length=50, verbose_name='Şifre')),
                ('address', models.CharField(max_length=50, verbose_name='Adres')),
                ('image', models.FileField(upload_to=None, verbose_name='Profil Fotğrafı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
