# Generated by Django 4.1.5 on 2023-02-22 16:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('appBitirme', '0005_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=50, null=True, region=None, verbose_name='Telefon Numarası'),
        ),
    ]
