# Generated by Django 4.1.5 on 2023-02-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBitirme', '0006_remove_userinfo_phone_userinfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Adres'),
        ),
    ]
