# Generated by Django 4.1.5 on 2023-02-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBitirme', '0007_alter_userinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.FileField(upload_to=None, verbose_name='Profil Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
