# Generated by Django 4.1.5 on 2023-02-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBitirme', '0008_alter_userinfo_image_alter_userinfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default='Adres', max_length=100, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.FileField(default='None/defaultProfil.webp', upload_to=None, verbose_name='Profil Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(default='Telefon Numarası', max_length=50, null=True, verbose_name='05---------'),
        ),
    ]
