# Generated by Django 4.1.5 on 2023-02-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBitirme', '0009_alter_userinfo_address_alter_userinfo_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('email', models.EmailField(max_length=254, verbose_name='Mail')),
                ('title', models.CharField(max_length=50, verbose_name='Konu')),
                ('text', models.TextField(max_length=500, verbose_name='Mesaj')),
            ],
        ),
    ]
