# Generated by Django 4.1.5 on 2023-03-18 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appBitirme', '0012_remove_card_category_card_categorys_alter_card_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SepetUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplamFiyat', models.FloatField(default=0, verbose_name='Toplam Fiyat')),
                ('adet', models.IntegerField(default=0, verbose_name='Adet')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBitirme.card', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
