# Generated by Django 4.1.5 on 2023-03-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBitirme', '0014_sepeturun_urunadet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepeturun',
            name='urunadet',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='urunadet',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ürün Adet'),
        ),
    ]
