# Generated by Django 4.1.5 on 2023-03-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBitirme', '0015_remove_sepeturun_urunadet_userinfo_urunadet'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='text',
            field=models.TextField(null=True, verbose_name='Ürün Özellikleri'),
        ),
    ]
