# Generated by Django 4.1.5 on 2023-03-23 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appBitirme', '0016_card_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star',
            field=models.IntegerField(default=0, verbose_name='Yorum Puanı'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(max_length=1000, null=True, verbose_name='Ürün Özellikleri'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yorumcu'),
        ),
    ]
