# Generated by Django 4.1.5 on 2023-03-27 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBitirme', '0023_beden_ebeden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebeden',
            name='beden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBitirme.beden', verbose_name='Beden'),
        ),
    ]
