# Generated by Django 4.1.5 on 2023-03-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBitirme', '0024_alter_ebeden_beden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepeturun',
            name='urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBitirme.ebeden', verbose_name='Ürün'),
        ),
    ]
