# Generated by Django 4.1.5 on 2023-03-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBitirme', '0026_numara_anumara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numara',
            name='slug',
        ),
    ]
