# Generated by Django 4.1.5 on 2023-03-27 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBitirme', '0027_remove_numara_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anumara',
            name='beden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBitirme.numara', verbose_name='Numara'),
        ),
        migrations.AlterField(
            model_name='numara',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Numara'),
        ),
    ]
