# Generated by Django 4.1.5 on 2023-03-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBitirme', '0029_remove_sepeturun_urun_sepeturun_aurun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepeturun',
            name='urun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appBitirme.card', verbose_name='ürün'),
        ),
        migrations.AlterField(
            model_name='sepeturun',
            name='Aurun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appBitirme.anumara', verbose_name='AÜrün'),
        ),
        migrations.AlterField(
            model_name='sepeturun',
            name='Eurun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appBitirme.ebeden', verbose_name='EÜrün'),
        ),
    ]
