# Generated by Django 4.1.5 on 2023-03-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBitirme', '0030_sepeturun_urun_alter_sepeturun_aurun_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepeturun',
            name='urun',
        ),
    ]
